import { NextRequest, NextResponse } from "next/server";

interface PushFile {
    filename: string;
    content: string;
}

export async function POST(req: NextRequest) {
    try {
        const body = await req.json();
        const {
            repoName,
            files,
            description,
            isPrivate = false,
            includeReadme = true,
            includeGitignore = true,
        } = body;

        const token = process.env.GITHUB_TOKEN;
        if (!token) {
            return NextResponse.json({ error: "GitHub token not configured. Add GITHUB_TOKEN to .env.local" }, { status: 500 });
        }

        if (!repoName || !files || !Array.isArray(files) || files.length === 0) {
            return NextResponse.json({ error: "Missing repoName or files" }, { status: 400 });
        }

        const headers = {
            Authorization: `Bearer ${token}`,
            Accept: "application/vnd.github+json",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        };

        // Step 1: Create repository
        const createRes = await fetch("https://api.github.com/user/repos", {
            method: "POST",
            headers,
            body: JSON.stringify({
                name: repoName,
                description: description || `Architecture files generated by Antigravity Symphony`,
                private: isPrivate,
                auto_init: includeReadme,
            }),
        });

        const repoData = await createRes.json();

        if (!createRes.ok) {
            // Provide helpful error messages
            if (createRes.status === 401) {
                throw new Error("Invalid GitHub token. Check GITHUB_TOKEN in .env.local");
            }
            if (createRes.status === 422 && repoData.message?.includes("name already exists")) {
                throw new Error(`Repository "${repoName}" already exists. Choose a different name.`);
            }
            throw new Error(repoData.message || `GitHub API error (${createRes.status})`);
        }

        const owner = repoData.owner.login;
        const repo = repoData.name;

        // Small delay to let GitHub finish initializing
        await new Promise((resolve) => setTimeout(resolve, 2000));

        // Step 2: Add .gitignore if requested
        if (includeGitignore) {
            const gitignoreContent = `# Dependencies
node_modules/
.pnp/
.pnp.js

# Build
.next/
out/
build/
dist/

# Environment
.env
.env.local
.env.*.local

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
`;
            const encoded = Buffer.from(gitignoreContent).toString("base64");
            await fetch(
                `https://api.github.com/repos/${owner}/${repo}/contents/.gitignore`,
                {
                    method: "PUT",
                    headers,
                    body: JSON.stringify({
                        message: "Add .gitignore — generated by Antigravity Symphony",
                        content: encoded,
                    }),
                }
            );
        }

        // Step 3: Commit each architecture file
        const committedFiles: string[] = [];
        const failedFiles: string[] = [];

        for (const file of files as PushFile[]) {
            const fileName = file.filename;
            const content = file.content;

            // Security: Validate fileName to prevent path traversal
            if (!/^[a-zA-Z0-9._-]+$/.test(fileName) || fileName.includes("..")) {
                console.warn(`Skipping invalid filename: ${fileName}`);
                failedFiles.push(fileName);
                continue;
            }

            const encoded = Buffer.from(content).toString("base64");

            const putRes = await fetch(
                `https://api.github.com/repos/${owner}/${repo}/contents/${fileName}`,
                {
                    method: "PUT",
                    headers,
                    body: JSON.stringify({
                        message: `Add ${fileName} — generated by Antigravity Symphony`,
                        content: encoded,
                    }),
                }
            );

            if (!putRes.ok) {
                const err = await putRes.json();
                console.error(`Failed to commit ${fileName}:`, err);
                failedFiles.push(fileName);
                continue;
            }

            committedFiles.push(fileName);
        }

        return NextResponse.json({
            repoUrl: repoData.html_url,
            owner,
            repo,
            committedFiles,
            failedFiles,
        });
    } catch (err: unknown) {
        console.error("GitHub push error:", err);
        const message = err instanceof Error ? err.message : "GitHub push failed";
        return NextResponse.json({ error: message }, { status: 500 });
    }
}
