import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
    try {
        const { repoName, files, description } = await req.json();

        const token = process.env.GITHUB_TOKEN;
        if (!token) {
            return NextResponse.json({ error: "GitHub token not configured" }, { status: 500 });
        }

        if (!repoName || !files || typeof files !== "object") {
            return NextResponse.json({ error: "Missing repoName or files" }, { status: 400 });
        }

        const headers = {
            Authorization: `Bearer ${token}`,
            Accept: "application/vnd.github+json",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        };

        // Step 1: Create repository
        const createRes = await fetch("https://api.github.com/user/repos", {
            method: "POST",
            headers,
            body: JSON.stringify({
                name: repoName,
                description: description || `Architecture files generated by Antigravity Symphony`,
                private: false,
                auto_init: true,
            }),
        });

        const repoData = await createRes.json();

        if (!createRes.ok) {
            throw new Error(repoData.message || "Failed to create repository");
        }

        const owner = repoData.owner.login;
        const repo = repoData.name;

        // Small delay to let GitHub finish initializing
        await new Promise((resolve) => setTimeout(resolve, 2000));

        // Step 2: Commit each file
        const committedFiles: string[] = [];

        for (const [fileName, content] of Object.entries(files)) {
            // Base64 encode the content
            const encoded = Buffer.from(content as string).toString("base64");

            const putRes = await fetch(
                `https://api.github.com/repos/${owner}/${repo}/contents/${fileName}`,
                {
                    method: "PUT",
                    headers,
                    body: JSON.stringify({
                        message: `Add ${fileName} — generated by Antigravity Symphony`,
                        content: encoded,
                    }),
                }
            );

            if (!putRes.ok) {
                const err = await putRes.json();
                console.error(`Failed to commit ${fileName}:`, err);
                continue;
            }

            committedFiles.push(fileName);
        }

        return NextResponse.json({
            repoUrl: repoData.html_url,
            owner,
            repo,
            committedFiles,
        });
    } catch (err: unknown) {
        console.error("GitHub push error:", err);
        const message = err instanceof Error ? err.message : "GitHub push failed";
        return NextResponse.json({ error: message }, { status: 500 });
    }
}
