"use client";

import { useState } from "react";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import {
    Download,
    Github,
    Loader2,
    Check,
    ExternalLink,
} from "lucide-react";

interface ExportActionsProps {
    files: Record<string, string>;
    projectName: string;
}

export default function ExportActions({
    files,
    projectName,
}: ExportActionsProps) {
    const [downloading, setDownloading] = useState(false);
    const [pushing, setPushing] = useState(false);
    const [repoUrl, setRepoUrl] = useState<string | null>(null);
    const [error, setError] = useState<string | null>(null);

    const handleDownloadZip = async () => {
        setDownloading(true);
        try {
            const zip = new JSZip();
            const folder = zip.folder(projectName) || zip;

            Object.entries(files).forEach(([name, content]) => {
                folder.file(name, content);
            });

            const blob = await zip.generateAsync({ type: "blob" });
            saveAs(blob, `${projectName}-architecture.zip`);
        } catch (err) {
            console.error("ZIP error:", err);
        } finally {
            setDownloading(false);
        }
    };

    const handlePushToGitHub = async () => {
        setPushing(true);
        setError(null);
        try {
            const repoName = projectName
                .toLowerCase()
                .replace(/[^a-z0-9-]/g, "-")
                .replace(/-+/g, "-")
                .replace(/^-|-$/g, "");

            const res = await fetch("/api/github-push", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    repoName: `${repoName}-architecture`,
                    files,
                    description: `Architecture files for ${projectName}, generated by Antigravity Symphony`,
                }),
            });

            const data = await res.json();

            if (!res.ok) {
                throw new Error(data.error || "GitHub push failed");
            }

            setRepoUrl(data.repoUrl);
        } catch (err: unknown) {
            const message = err instanceof Error ? err.message : "Push failed";
            setError(message);
        } finally {
            setPushing(false);
        }
    };

    return (
        <div className="flex flex-wrap items-center gap-3">
            {/* Download ZIP */}
            <button
                onClick={handleDownloadZip}
                disabled={downloading}
                className="btn-primary text-sm py-2.5 px-5"
            >
                {downloading ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                    <Download className="h-4 w-4" />
                )}
                Download ZIP
            </button>

            {/* Push to GitHub */}
            {repoUrl ? (
                <a
                    href={repoUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="btn-secondary text-sm py-2.5 px-5 text-success border-success/30"
                >
                    <Check className="h-4 w-4" /> View Repository{" "}
                    <ExternalLink className="h-3 w-3" />
                </a>
            ) : (
                <button
                    onClick={handlePushToGitHub}
                    disabled={pushing}
                    className="btn-secondary text-sm py-2.5 px-5"
                >
                    {pushing ? (
                        <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                        <Github className="h-4 w-4" />
                    )}
                    Push to GitHub
                </button>
            )}

            {error && (
                <p className="w-full text-xs text-danger mt-1">{error}</p>
            )}
        </div>
    );
}
